name: Docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code    
        uses: actions/checkout@v2.2.0
      - name: Build Docker images for Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: junghans/rawhide-latex
          dockerfile: .github/workflows/Dockerfile
          push: false
